### ISSUE TITLE
"kubectl describe node" doesn't show the Allocatable MLU270 corretly

### ISSUE THREAD

**Issue by xlvy** [Cambricon/cambricon-k8s-device-plugin#10]
The command "kubectl describe node" shows the MLU100 correctly, but MLU 270 is failed, the command output is as follows：

![image](https://user-images.githubusercontent.com/51997291/103603135-d2ee3c00-4f48-11eb-8f3a-9a6adac33d1a.png)

**Comment by yttan** [comment]
Using MLUs together with GPUs at the same server is not supported.
