### ISSUE TITLE
build device plugin failed

### ISSUE THREAD

**Issue by mingfengwuye** [Cambricon/cambricon-k8s-device-plugin#12]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Issue or feature description
Please provide a source image with 'from' prior to commit
Error response from daemon: reference dose not exist
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)
<img width="385" alt="0df69c47428b190b4581093fb7b11ada-31024" src="https://user-images.githubusercontent.com/13177804/127282763-65ce69a1-1672-42c3-802f-f4c7fe2bdb61.png">

**Comment by mingfengwuye** [comment]
docker version is low, please update docker to latest version

**Comment by yttan** [comment]
Please upgrade you docker version on your compiling machine, it should be at least docker 17.05.0-ce.

See more details here: https://github.com/moby/moby/pull/31352

**Comment by YuxiJin-tobeyjin** [comment]
add  in readme ?

**Comment by yttan** [comment]
building prerequests updated in readme.
