### ISSUE TITLE
贵司有扩展调度器的开放源码么

### ISSUE THREAD

**Issue by dabaoa** [Cambricon/cambricon-k8s-device-plugin#15]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

mlu-share: mlu resources are allocated by memory. Only works when deployed along with Cambricon MLU Scheduler Extender.
看了你们的说明文档，现在也是支持mlu 虚拟化的，但是需要使用你们的扩展调度器，请问有这个源码

**Comment by YuxiJin-tobeyjin** [comment]
这部分暂不支持开源
