### ISSUE TITLE
dynamic-smlu模式疑问

### ISSUE THREAD

**Issue by haozhou-wong** [Cambricon/cambricon-k8s-device-plugin#18]
您好，我看文档中有写 supports dynamic-smlu mode, now only 370 support dynamic-smlu, need to use accompony with scheduler extender，有几个问题想请教一下。
1. 请问这个dynamic-smlu模式具体是指什么？有相关文档说明吗？我在寒武纪社区里cnmon文档里有看到smlu模式，这两个是一个东西吗，使用dynamic-smlu之前需要用cnmon将smlu设置为on吗？
2. 需要与scheduler extender协作，这个调度器插件要去哪里找呢？还是说需要自己实现？如果需要自己实现的话，有相关的文档指导吗？

**Comment by YuxiJin-tobeyjin** [comment]
Hello, `dynamic-smlu` mode needs to be used with scheduler extender. Scheduler extender currently has no plan for open source . You can contact our AE to obtain the image and corresponding user guide.

**Comment by ZSL98** [comment]
Could you please provide the contact info of AE? Or any linkage?

**Comment by rayroot** [comment]
> Could you please provide the contact info of AE? Or any linkage? @YuxiJin-tobeyjin
sales@cambricon.com
or
service@cambricon.com
