### ISSUE TITLE
error: unable to recognize "cambricon-device-plugin.yml": no matches for kind "DaemonSet" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by zhwork92d** [Cambricon/cambricon-k8s-device-plugin#6]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._
---

### 1. Issue or feature description
exec this command "kubectl create -f cambricon-device-plugin.yml" 
show the error : 
 error: unable to recognize "cambricon-device-plugin.yml": no matches for kind "DaemonSet" in version "extensions/v1beta1"

my kuubenets version is v1.18.3 .
how to deal with this problem ?

**Comment by YuxiJin-tobeyjin** [comment]
Yes， since k8s 1.18.3 no longer supports "extensions/v1beta1”， the yaml needs to be updated.
